baseurl = "https://wohmy.com/"
languageCode = "zh-cn"
title = "GodHao Blog"
DefaultContentLanguage = "zh"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5

[params]
title = "wohmy.com"
description = "GodHao Blog"
# gravatar = "godhao520@aliyun.com"
images = ["images/profile.png"]
profilePicture = "images/profile.png"
copyright = "GodHao"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
builtWith = true
mainSections = ["post"]

## Set custom theme color.
# themeColor = "#fc2803"

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "#"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/GodHaoNB/GodHaoNB.github.io.git"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "#"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

 

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4
